@echo off
@color 3D
@mode con: lines=7 cols=80

set var1=  _______   ____       _____       _         _____       _   __      _____
set var2= \      /  !  __!     !  _  !     ! !       !  _  !     ! ! / /     !  _  !
set var3=  \ __ /   ! !        ! !_! !     ! !       ! ! ! !     ! !/ /      ! !_! !
set var4=  /    \   ! !__   _  ! ! ! !  _  ! !_   _  ! !_! !  _  ! !\ \   _  ! ! ! !
set var5= /______\  !____! !_! !_! !_! !_! !___! !_! !_____! !_! !_! \_\ !_! !_! !_!




echo %var1%
echo %var2%
echo %var3%
echo %var4%
echo %var5%
pause
